// import.js — Standalone import page for Firefox (programmatic file input restricted in extension popups).

document.addEventListener('DOMContentLoaded', () => {
    const titleApp = chrome.i18n.getMessage("appTitle");
    const titleImport = chrome.i18n.getMessage("importBtn");

    document.title = `${titleImport} - ${titleApp}`;
    document.getElementById('app-title').textContent = titleApp;

    const importBtn = document.getElementById('import-action-btn');
    importBtn.textContent = titleImport;

    const fileInput = document.getElementById('file-input');
    const statusMsg = document.getElementById('status-msg');

    importBtn.addEventListener('click', () => fileInput.click());

    fileInput.addEventListener('change', (e) => {
        const file = e.target.files[0];
        if (!file) return;

        const reader = new FileReader();
        reader.onload = async (event) => {
            try {
                const importedData = JSON.parse(event.target.result);
                await mergeImportData(importedData);
                statusMsg.textContent = chrome.i18n.getMessage("alertImportSuccess") || "Import successful! Your folders and prompts have been merged successfully.";
                statusMsg.style.color = "green";
                fileInput.value = "";
            } catch (error) {
                console.error("Import error:", error);
                statusMsg.textContent = chrome.i18n.getMessage("alertImportError") || "Import error. Make sure it's a valid JSON file generated by this extension.";
                statusMsg.style.color = "red";
                fileInput.value = "";
            }
        };
        reader.readAsText(file);
    });
});
